title: Kyle Tov
email: kyle.tov@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my online portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: kyletov
linkedin_username: kyletov

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

collections:
  posts:
    output          : true
  projects:
    output          : true
